# บอกให้ Spring Boot ใช้ค่า Environment Variables ที่ Render จะสร้างให้เรา
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# สั่งให้ Hibernate (JPA) สร้างหรืออัปเดตตารางในฐานข้อมูลให้เราอัตโนมัติตอนโปรแกรมเริ่มทำงาน
spring.jpa.hibernate.ddl-auto=update