# PostgreSQL Settings for Production Server (Render.com)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Create or update database tables automatically
spring.jpa.hibernate.ddl-auto=update