# ที่อยู่ของฐานข้อมูล MySQL บนเครื่องของคุณ
spring.datasource.url=jdbc:mysql://localhost:3306/ihavecfu_db

# Username และ Password ที่เราสร้างขึ้น
spring.datasource.username=pao
spring.datasource.password=admin

# บอก Hibernate ให้ใช้ภาษาของ MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ให้ Hibernate สร้าง/อัปเดตตารางให้เราโดยอัตโนมัติ
spring.jpa.hibernate.ddl-auto=update